-- Use this block from SYSTEM user
-- CREATE USER system IDENTIFIED BY "Stryker_11";
-- GRANT ALL PRIVILEGES TO system;

-- Use this block from SYSTEM user
CREATE SEQUENCE Hotel_Booking;
CREATE TABLE Hotel(
    HOTEL_ID NUMBER NOT NULL,
    HOTEL_NAME VARCHAR(20),
    ADDRESS VARCHAR(20),
    HOTEL_PHONE NUMBER,

    CONSTRAINT PK_HOTEL PRIMARY KEY (HOTEL_ID)
);

CREATE TABLE Room(
    ROOM_ID NUMBER NOT NULL,
    HOTEL_ID NUMBER NOT NULL,
    ROOM_NUM NUMBER NOT NULL,
    ROOM_PRICE FLOAT,
    ROOM_STATUS VARCHAR(10),
    CANCEL_RISK FLOAT,

    CONSTRAINT PK_ROOM PRIMARY KEY (ROOM_ID)
);

CREATE TABLE Customer(
    CUS_ID NUMBER NOT NULL,
    CUS_FNAME VARCHAR(20),
    CUS_LNAME VARCHAR(20),
    CUS_EMAIL VARCHAR(20) NOT NULL,
    CUS_PHONE NUMBER,

    CONSTRAINT PK_CUS PRIMARY KEY (CUS_ID)
);

CREATE TABLE Payment(
    PAY_ID NUMBER NOT NULL,
    RES_ID NUMBER NOT NULL,
    PAY_DATE DATE,
    PAY_AMOUNT FLOAT,
    PAY_STATUS VARCHAR(10),

    CONSTRAINT PK_PAYMENT PRIMARY KEY (PAY_ID)
);

CREATE TABLE Reservation(
    RES_ID NUMBER,
    CUS_ID NUMBER,
    ROOM_ID NUMBER,
    RES_DATE DATE,
    RES_STATUS VARCHAR(20),
    TOTAL_COST FLOAT,

    CONSTRAINT PK_RES PRIMARY KEY (RES_ID)
);

CREATE TABLE Service(
    SERV_PHONE NUMBER,
    RES_ID NUMBER,
    SERV_TYPE VARCHAR(20),
    SERV_PRICE FLOAT,

    CONSTRAINT PK_SERVICE PRIMARY KEY (SERV_PHONE, RES_ID)
);

ALTER TABLE Room
ADD CONSTRAINT FK_Room
FOREIGN KEY (HOTEL_ID)
REFERENCES Hotel(HOTEL_ID);

ALTER TABLE Reservation
ADD CONSTRAINT FK_Res
FOREIGN KEY (CUS_ID, ROOM_ID)
REFERENCES Customer(CUS_ID), Room(ROOM_ID);

ALTER TABLE Service
ADD CONSTRAINT FK_Service
FOREIGN KEY (RES_ID)
REFERENCES Reservation(RES_ID);

ALTER TABLE Payment
ADD CONSTRAINT FK_Payment
FOREIGN KEY (RES_ID)
REFERENCES Reservation(RES_ID);