-- Use this block from SYSTEM user
-- CREATE USER system IDENTIFIED BY "Stryker_11";
-- GRANT ALL PRIVILEGES TO system;

-- Use this block from SYSTEM user
CREATE SEQUENCE Hotel_Booking;
CREATE TABLE Hotel(
    HOTEL_ID NUMBER NOT NULL,
    HOTEL_NAME VARCHAR(20),
    ADDRESS VARCHAR(20),
    HOTEL_PHONE NUMBER,

    CONSTRAINT PK_HOTEL PRIMARY KEY (HOTEL_ID)
);

CREATE TABLE Room(
    ROOM_ID NUMBER NOT NULL,
    HOTEL_ID NUMBER NOT NULL,
    ROOM_NUM NUMBER NOT NULL,
    ROOM_PRICE FLOAT,
    ROOM_STATUS VARCHAR(10),
    CANCEL_RISK FLOAT,

    CONSTRAINT PK_ROOM PRIMARY KEY (ROOM_ID)
);

CREATE TABLE Customer(
    CUS_ID NUMBER NOT NULL,
    CUS_FNAME VARCHAR(20),
    CUS_LNAME VARCHAR(20),
    CUS_EMAIL VARCHAR(20) NOT NULL,
    CUS_PHONE NUMBER,

    CONSTRAINT PK_CUS PRIMARY KEY (CUS_ID)
);

CREATE TABLE Payment(
    PAY_ID NUMBER NOT NULL,
    RES_ID NUMBER NOT NULL,
    PAY_DATE DATE,
    PAY_AMOUNT FLOAT,
    PAY_STATUS VARCHAR(10),

    CONSTRAINT PK_PAYMENT PRIMARY KEY (PAY_ID)
);

ALTER TABLE Room
ADD CONSTRAINT FK_Room
FOREIGN KEY (HOTEL_ID)
REFERENCES Hotel(HOTEL_ID);